# These are supported funding model platforms

github: ['dabble-of-devops-bioanalyze'] 
custom: ['https://www.paypal.com/donate/?hosted_button_id=DJUYA2BA85NNL'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
