ingress:
  enabled: true
  tls: true
  apiVersion: ''
  pathType: ImplementationSpecific
  certManager: true
  hostname: nginx1.bioanalyzedev.io
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: nginx1-letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /
  extraHosts:
  - hosts:
    - nginx1.bioanalyzedev.io
    secretName: nginx1.local-tls
service:
  type: ClusterIP
  port: 80
